name: build and deploy to pages 🥳

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages

    strategy:
      matrix:
        node-version:
          - 22.x

    steps:
      - name: checkout code 💣
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        run: npm ci

      - name: Build the app 👾
        env:
          VITE_IMG_PATH: /dogeMage/mage.gif
          VITE_COIN_IMG_PATH: /dogeMage/dodg.gif
          VITE_GAME_OVER_GIRL_PATH: /dogeMage/gameOverGirl.png
          VITE_PARTITION_KEY: ${{ vars.VITE_PARTITION_KEY }}
          VITE_SCOREBOARD_RESULTS_ENDPOINT: ${{ vars.VITE_SCOREBOARD_RESULTS_ENDPOINT }}
          VITE_POST_NEW_SCORE_ENDPOINT: ${{ vars.VITE_POST_NEW_SCORE_ENDPOINT }}
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
