name: run unit tests 📚

on:
  push:
    branches:
      - "*"
      - "!master" # covered by the pr run
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 22.x

    steps:
      - name: checkout code 💣
        uses: actions/checkout@v3

      - name: create .env file for tests 💫
        run: |
          touch .env
          echo VITE_IMG_PATH='dogeMage/mage.gif' > .env
          echo VITE_COIN_IMG_PATH='dogeMage/dodg.gif' >> .env
          echo VITE_GAME_OVER_GIRL_PATH='dogeMage/gameOverGirl.png' >> .env

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        run: npm ci

      - name: run tests 🤌
        run: |
          npm run unit-test
